name: Java CI

on:
    push:
    pull_request:
        branches:
            - main

jobs:
    Build:
        strategy:
            matrix:
                jdkversion: [ 17 ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.jdkversion }}
                  cache: 'maven'
            - name: Build
              run: mvn -V -B clean package --file pom.xml
            - name: Upload Bukkit Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: Download-Bukkit
                  path: ./bukkit/target/AdvancedSensitiveWords-bukkit.jar
            - name: Upload Velocity Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: Download-Velocity
                  path: ./velocity/target/AdvancedSensitiveWords-velocity.jar
            - name: Upload BungeeCord Artifacts
              uses: actions/upload-artifact@v3.1.2
              with:
                  name: Download-BungeeCord
                  path: ./bungee/target/AdvancedSensitiveWords-bungee.jar
    runtime-test:
        name: Plugin Runtime Test
        needs: [Build]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - mcVersion: '1.8.8'
                      javaVersion: '8'
                    - mcVersion: '1.12.2'
                      javaVersion: '8'
                    - mcVersion: '1.20.2'
                      javaVersion: '20'
        steps:
            - uses: HaHaWTH/minecraft-plugin-runtime-test@paper
              with:
                  server-version: ${{ matrix.mcVersion }}
                  java-version: ${{ matrix.javaVersion }}
                  artifact-name: Download-Bukkit
